In [1]:
import numpy as np
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [2]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [3]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [4]:
A = np.random.randn(10)
A

array([ 0.43065016, -0.3443423 ,  0.6666871 , -2.28999758, -2.25024413,
       -1.98310898,  0.65162455, -1.02295416, -0.50241111,  0.76391964])

In [5]:
B = np.random.randn(10)

In [6]:
B

array([-0.87815048, -0.93808681,  1.34016765,  0.99195757,  0.29366697,
       -0.32388651, -1.39892398,  1.60815247, -2.26200191,  0.17287492])

In [7]:
# Binary Functions
np.add(A,B)

array([-0.44750032, -1.2824291 ,  2.00685475, -1.29804002, -1.95657716,
       -2.30699549, -0.74729943,  0.58519831, -2.76441303,  0.93679456])

In [8]:
np.maximum(A,B)

array([ 0.43065016, -0.3443423 ,  1.34016765,  0.99195757,  0.29366697,
       -0.32388651,  0.65162455,  1.60815247, -0.50241111,  0.76391964])

In [11]:
website = 'http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufucs'
import webbrowser
webbrowser.open(website)

True